(() => {
 'use strict';
 const D=window.JX_DEMO_DATA,M=window.JXModel,S=window.JX_SCHEMA,C=window.JX_CHOICES,W=window.JXWorkspace,P=window.JXPlatform,V=window.JXValidation,$=id=>document.getElementById(id);
 const originals=new Map(D.skills.map(s=>[s.id,s])),missiles=new Map(D.missiles.map(s=>[s.id,s]));
 const drafts=new Map(),missileDrafts=new Map(),formulaDrafts=new Map(),assetDrafts=new Map();
 let workspaceLoaded=false,lastContent='',manualSavedContent='',pendingWorkspace=null,validation=null;
 let selected=4,limit=80,activeTab='general',missileId=null,createKind='skill',creationParent=null,resourceSave=null;
 const animation=window.JXAnimation.player($('animation-preview')),actionAnimation=window.JXAnimation.player($('action-preview')),resourceAnimation=window.JXAnimation.player($('resource-preview'));
 let castStages=[];
 const baseline=s=>s.isNew?Object.fromEntries(D.headers.map(k=>[k,''])):originals.get(s.id).fields;
 const missileBaseline=m=>m.isNew?Object.fromEntries(D.missileHeaders.map(k=>[k,''])):missiles.get(m.id).fields;
 const clone=o=>JSON.parse(JSON.stringify(o));
 const current=()=>drafts.get(selected)||originals.get(selected);
 const skill=id=>drafts.get(id)||originals.get(id);
 const allSkills=()=>[...originals.keys()].map(skill);
 const status=text=>{$('status').textContent=text;};
 const updateState=text=>{const el=$('update-state');if(el)el.textContent=text;};
 function onUpdateEvent(name,data){
  const d=data||{};
  if(name==='host.updateChecking'){updateState('Đang kiểm tra cập nhật…');return;}
  if(name==='host.updateAvailable'){updateState('Có bản '+(d.version||'mới')+' · đang hỏi xác nhận');return;}
  if(name==='host.updateProgress'){
   const received=Math.round(Number(d.received||0)/1000000),total=Number(d.total||0)>0?Math.round(Number(d.total)/1000000):0;
   updateState(total?'Đang tải cập nhật · '+received+' / '+total+' MB':'Đang tải cập nhật · '+received+' MB');return;
  }
  if(name!=='host.updateStatus')return;
  if(d.status==='up-to-date')updateState('Đã kiểm tra · bản '+(d.version||d.current||'hiện tại'));
  else if(d.status==='declined')updateState('Đã bỏ qua bản '+(d.version||'mới'));
  else if(d.status==='downloading')updateState('Đang tải bản '+(d.version||'mới')+'…');
  else if(d.status==='ready')updateState('Đang khởi động bản '+(d.version||'mới')+'…');
  else if(d.status==='failed')updateState('Cập nhật lỗi · '+(d.error||'hãy thử lại'));
 }
 P.onUpdate?.(onUpdateEvent);
 const clean=s=>String(s??'').replace(/<enter>/gi,'\n').replace(/<[^>]*>/g,'').replace(/^"|"$/g,'').trim();
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 function makeButton(text,fn,cls='button'){const b=node('button',text,cls);b.type='button';b.onclick=fn;return b;}
 function iconUrl(s){if(assetDrafts.has(s.id))return assetDrafts.get(s.id).preview;const matched=D.skills.find(x=>x.fields.SkillIcon===s.fields.SkillIcon&&x.icon);return matched?D.icons[matched.icon.key]:null;}
 function drawIcon(el,s){el.replaceChildren();const url=iconUrl(s);if(url){const img=document.createElement('img');img.src=url;img.alt='Icon '+s.fields.SkillName;el.append(img);}else el.textContent='劍';}
 function factionText(s){return s.factionName+(s.scope==='learned'?' · có lệnh học':s.scope==='new'?' · draft mới':' · chưa xác minh học');}
 function choose(id){if(!originals.has(id)){status('Không tìm thấy SkillId '+id);return;}selected=id;missileId=null;renderList();renderEditor();}
 function renderList(){const list=M.filterSkills(allSkills(),{query:$('search').value,faction:$('faction').value,scope:$('scope').value});$('count').textContent=list.length+' kết quả / '+D.coverage.rows+' ID gốc';const fragment=document.createDocumentFragment();list.slice(0,limit).forEach(s=>{const b=makeButton('',()=>choose(s.id),'skill-row'+(selected===s.id?' active':''));b.setAttribute('aria-pressed',String(selected===s.id));const icon=node('span',undefined,'skill-icon');drawIcon(icon,s);const text=node('span');text.append(node('strong',s.fields.SkillName),node('small','#'+s.id+' · '+s.factionName));b.append(icon,text);fragment.append(b);});if(list.length>limit)fragment.append(makeButton('Xem thêm 80 skill',()=>{limit+=80;renderList();}));if(!list.length)fragment.append(node('p','Không có kết quả ở phạm vi đang chọn.','empty'));$('skill-list').replaceChildren(fragment);}
 function editSkill(key,value){const s=clone(current());s.fields[key]=value;drafts.set(selected,s);renderList();renderHeader();renderPreview();renderDiff();previewCast();status('Đã sửa '+key+' trong draft #'+selected);}
 function resourceOptions(){return C.resources.filter(r=>!r.uses.every(x=>x.startsWith('Action '))).map(r=>({value:r.path,label:(r.status==='ready'?'▶ ':'⚠ ')+r.path.split('\\').pop()+' · '+r.uses[0],description:r.status==='ready'?r.frames+' frame · '+r.directions+' hướng · '+r.container:r.reason,source:r.path}));}
 function referenceOptions(kind){const list=kind==='missile'?[...new Set([...missiles.keys(),...missileDrafts.keys()])].map(id=>missileDrafts.get(id)||missiles.get(id)):allSkills();return [{value:'0',label:'Không liên kết',description:'Không gắn ID ở vị trí này.'},...list.map(x=>({value:String(x.id),label:x.fields.SkillName||x.fields.MissleName,description:(kind==='missile'?'Đường đạn':'Skill / tầng')+' #'+x.id+' · '+(x.fields.SkillName||x.fields.MissleName),source:x.isNew?'Draft mới':kind==='missile'?D.missileSource:D.source}))];}
 function optionsFor(key){
  if(key==='ChildSkillId')return referenceOptions(current().fields.BaseSkill==='1'||current().fields.ByMissle==='1'?'missile':'skill');
  if(['StartSkillId','FlySkillId','CollidSkillId','VanishedSkillId','ResponseSkill'].includes(key))return referenceOptions('skill');
  if(key==='EqtLimit'||key==='Attrib')return Object.entries(key==='Attrib'?D.settings.SkillAttrib:D.settings.WeaponLimit).map(([v,t])=>({value:v==='F1'?'-1':v==='F2'?'-2':v,label:clean(t),description:clean(t),source:'gamesetting.ini ['+(key==='Attrib'?'SkillAttrib':'WeaponLimit')+']'}));
  if(/^LvlSetting\d+$/.test(key))return [...new Set([...D.skills.flatMap(x=>M.slots(x.fields).map(t=>t.property)),...Object.keys(M.statLabels)])].filter(Boolean).sort().map(value=>({value,label:M.statLabels[value]||value,description:M.statLabels[value]||'Thuộc tính có trong bảng client; P1/P2/P3 theo Lua, chưa có mô tả riêng.',source:'skills.txt / script/skill'}));
  if(/^LvlData\d+$/.test(key)){const script=D.scripts[current().fields.LvlSetScript];return [...new Set([...Object.keys(script?.tables||{}),'skill_'+selected])].map(value=>({value,label:value,description:value==='skill_'+selected?'Khóa riêng cho skill #'+selected:'Khóa có trong bảng Lua đang chọn.'}));}
  if(key==='PreCastSpr'||/^AnimFileB?\d$/.test(key))return resourceOptions();
  return C.enums[key]||null;
 }
 function resourceByPath(path){return C.resources.find(r=>r.path===path);}
 function previewAction(value=current().fields.CharAnimId){
  const actionId=String(value??''),a=C.actions.find(x=>x.value===actionId),timing=$('action-timing');
  if(!a?.code){actionAnimation.explain(a?.description||'Chưa chọn action; hãy chọn mã ở Cast & mục tiêu.','Action '+(value||'chưa khai báo'));if(timing)timing.textContent='';return;}
  const profile=C.profiles.find(p=>p.key===$('preview-character').value)||C.profiles[0],pose=profile?.poses.find(p=>p.value===$('preview-pose').value)||profile?.poses[0],mapped=pose?.actions?.[actionId];
  if(!mapped){actionAnimation.explain('Không có mapping cho tư thế đang chọn.');if(timing)timing.textContent='';return;}
  const layers=mapped.layers?.length?mapped.layers:[{name:'Body',path:mapped.path,label:'Thân'},{name:'Head',path:mapped.headPath,label:'Đầu'}].filter(x=>x.path);
  const main=layers.find(x=>x.path===mapped.path)||layers[0],mainResource=resourceByPath(main?.path),readyLayers=layers.filter(x=>x.path&&resourceByPath(x.path)?.status==='ready'),companions=readyLayers.filter(x=>x.path!==main?.path).map(x=>x.path);
  let overlayLabel='';
  if($('action-cast-overlay')?.checked){const stage=castStages[Number($('cast-stage')?.value)],effect=stage?.resource?.status==='ready'?stage:null;if(effect?.path&&!companions.includes(effect.path)&&effect.path!==main?.path){companions.push(effect.path);overlayLabel=' · ghép '+effect.label;}}
  const requested=Number($('action-interval')?.value)||0,interval=requested>0?Math.max(16,requested):0;
  if(mainResource?.status==='ready'&&main?.path)actionAnimation.show(main.path,'Action '+value+' · '+a.label+' · '+mapped.mapped,{companions,intervalMs:interval});else actionAnimation.explain(mainResource?.reason||'Chưa giải mã được SPR thân '+(main?.path||''),'Action '+value+' · '+a.label);
  if(timing){const header=mainResource?.interval||0,used=interval||header||0,missing=Math.max(0,layers.length-readyLayers.length),labels=readyLayers.map(x=>x.label||x.name).join(', ')||'chưa có lớp sẵn sàng';timing.textContent='Composite '+readyLayers.length+'/'+layers.length+' lớp · '+labels+' · '+(header?'header '+header+' ms/frame':'header chưa rõ')+(interval?' · override '+used+' ms/frame':' · đang dùng '+used+' ms/frame')+(missing?' · thiếu '+missing+' lớp chưa giải mã':'')+overlayLabel+'.';}
 }
 function previewCast(){const resolved=window.JXCast.resolve(selected,skill,id=>missileDrafts.get(id)||missiles.get(id),C.resources);castStages=resolved.stages;const select=$('cast-stage'),previous=select.value;select.replaceChildren();for(let i=0;i<castStages.length;i++){const o=node('option',castStages[i].label);o.value=String(i);select.append(o);}select.value=Number(previous)<castStages.length?previous:'0';if(!select.value&&castStages.length)select.value='0';$('cast-warning').textContent=resolved.warnings.join(' · ')||(!castStages.length?'Skill không có SPR hiệu ứng trực tiếp trong liên kết đã resolve.':'');showCastStage();}
 function showCastStage(){const stage=castStages[Number($('cast-stage').value)],f=current().fields;if(!stage){animation.explain('Không có SPR hiệu ứng trực tiếp cho skill này. Xem action nhân vật ở khung trên.');$('cast-timing').textContent='';previewAction();return;}const interval=Number($('cast-interval').value)||0,header=stage.resource?.interval||0,t=window.JXCast.timing(f,stage.missile,stage.resource,interval);$('cast-timing').textContent='Mô phỏng: WaitTime '+(f.WaitTime||0)+' tick ≈ '+t.waitMs+' ms · TimePerCast '+(f.TimePerCast||0)+' tick ≈ '+t.castMs+' ms · LifeTime '+(stage.missile?.fields.LifeTime||0)+' tick ≈ '+t.lifeMs+' ms · SPR '+(header||'chưa rõ')+' ms/frame'+(interval?' · đang xem '+t.frameIntervalMs+' ms/frame':'')+'. Tick giả định 18/s; chưa đối chiếu engine live.';if(stage.resource?.status==='ready')animation.show(stage.path,stage.label,{intervalMs:interval,autoplayDelayMs:t.waitMs});else animation.explain(stage.resource?.reason||'Chưa giải mã được SPR '+stage.path,stage.label);previewAction();}
 function previewSkill(id){const ref=skill(Number(id));if(!ref){animation.explain('Không có tầng liên kết.');return;}const target=M.childTarget(ref.fields),m=target?.kind==='missile'?(missileDrafts.get(target.id)||missiles.get(target.id)):null;
  const raw=m&&Object.entries(m.fields).find(([k,v])=>/^AnimFileB?\d$/.test(k)&&v)?.[1];
  if(raw)animation.show(raw,'Tầng #'+id+' · SPR đường đạn trực tiếp');else previewAction(ref.fields.CharAnimId);
 }
 function previewField(key,value){
  if(key==='CharAnimId')previewAction(value);
  else if(key==='PreCastSpr'||/^AnimFileB?\d$/.test(key))value?animation.show(value,key):animation.explain('Chưa chọn SPR cho '+key);
  else if(key==='StateSpecialId'){const state=C.states.find(x=>x.value===value);if(state?.path.endsWith('.spr'))animation.show(state.path,state.label);else animation.explain(state?'Trạng thái đặc biệt không trỏ trực tiếp đến SPR: '+state.path:'Không chọn trạng thái.');}
  else if(key==='ChildSkillId'&&(current().fields.BaseSkill==='1'||current().fields.ByMissle==='1')){const m=missileDrafts.get(Number(value))||missiles.get(Number(value));const raw=m&&Object.entries(m.fields).find(([k,v])=>/^AnimFileB?\d$/.test(k)&&v)?.[1];raw?animation.show(raw,'Đường đạn #'+value):animation.explain('Đường đạn này chưa gắn animation.');}
  else if(['ChildSkillId','StartSkillId','FlySkillId','CollidSkillId','VanishedSkillId'].includes(key))previewSkill(value);
 }
 function fieldControl(key,value,save,{readonly=false}={}){
  const label=node('label');label.append(node('span',S.labels[key]||key),node('small',key,'field-key'));let input,options=optionsFor(key);
  const isAnimation=key==='PreCastSpr'||/^AnimFileB?\d$/.test(key),canPreview=isAnimation||['CharAnimId','StateSpecialId','ChildSkillId','StartSkillId','FlySkillId','CollidSkillId','VanishedSkillId'].includes(key);
  const explanation=node('small',undefined,'choice-explanation'),source=node('small',undefined,'choice-source');
  if(key==='SkillDesc'){input=document.createElement('textarea');input.rows=4;}
  else if(options){input=document.createElement('select');options=[{value:'',label:'Chưa khai báo',description:'Chọn một giá trị để cấu hình.'},...options.filter(o=>o.value!=='')];if(!options.some(o=>o.value===String(value)))options.push({value:String(value??''),label:'Giá trị hiện tại chưa có nhãn',description:'Giữ nguyên giá trị nguồn; chưa suy nghĩa.'});
   const fill=query=>{input.replaceChildren();for(const o of options.filter(o=>o.value===String(value??'')||!query||(o.value+' '+o.label).toLowerCase().includes(query.toLowerCase()))){const opt=node('option',(o.value?o.value+' · ':'')+o.label);opt.value=o.value;input.append(opt);}input.value=value??'';};
   fill('');if(options.length>30){const filter=document.createElement('input');filter.type='search';filter.placeholder='Lọc lựa chọn…';filter.className='choice-filter';filter.setAttribute('aria-label','Lọc '+key);filter.oninput=()=>fill(filter.value);label.append(filter);}
  }else{input=document.createElement('input');input.type='text';}
  input.value=value??'';input.disabled=readonly;input.dataset.sourceField=key;input.setAttribute('aria-label',(S.labels[key]||key)+' · '+key);
  const help=()=>{const o=options?.find(o=>o.value===input.value);explanation.textContent=o?.description||'';explanation.hidden=!explanation.textContent;source.textContent=o?.source||'';};
  input.onchange=()=>{value=input.value;save(value);help();previewField(key,value);if(['BaseSkill','ByMissle'].includes(key)){renderGroup(S.groups.find(g=>g.key==='layers'));renderLayers();renderMissile();}else if(['ChildSkillId','StartSkillId','FlySkillId','CollidSkillId','VanishedSkillId'].includes(key)){renderLayers();renderMissile();}};label.append(input);if(options){help();label.append(explanation,source);}
  if(canPreview){const actions=node('div',undefined,'field-actions');actions.append(makeButton('▶ Xem animation',()=>previewField(key,input.value)));if(isAnimation)actions.append(makeButton('Chọn & xem SPR…',()=>openResource(input.value,raw=>{value=raw;save(raw);renderEditor();animation.show(raw,key);})));label.append(actions);}
  if(isAnimation){const raw=document.createElement('input');raw.value=value||'';raw.placeholder='Đường dẫn SPR khác';raw.setAttribute('aria-label','Đường dẫn riêng '+key);raw.onchange=()=>{save(raw.value);renderEditor();animation.show(raw.value,key);};const detail=node('details');detail.append(node('summary','Đường dẫn SPR tùy nhập'),raw);label.append(detail);}
  if(S.hints[key])label.append(node('small',S.hints[key],'field-hint'));if(key==='SkillDesc'||/Script|Spr|Snd|Icon|AnimFile|SndFile/.test(key)||key==='CharAnimId')label.classList.add('wide-field');return label;
 }
 function renderGroup(group){const el=$('fields-'+group.key);el.replaceChildren(...group.fields.filter(k=>D.headers.includes(k)).map(k=>fieldControl(k,current().fields[k],v=>editSkill(k,v))));}
 function renderHeader(){const s=current();drawIcon($('selected-icon'),s);$('skill-title').textContent=s.fields.SkillName;$('skill-meta').textContent='SKILL #'+s.id+' / '+factionText(s);$('skill-type').textContent=clean(D.settings.SkillAttrib[s.fields.Attrib]||s.fields.Property);$('source-warning').textContent=s.scope==='learned'?'Tên từ client · lệnh học trong snapshot server WSL đang chạy':s.scope==='new'?'Draft mới · chưa có lệnh học / chưa kiểm tra giới hạn ID':'Dòng gốc / tầng hoặc skill mở rộng · chưa chứng minh hiển thị trong bảng skill nhân vật';}
 function renderEditor(){renderHeader();for(const g of S.groups)renderGroup(g);renderDamage();renderLayers();renderMissile();renderAssets();renderRaw();renderPreview();renderDiff();previewCast();previewAction();}
 function formulaKey(script,key,property){return JSON.stringify([script,key,property]);}
 function definition(fields,slot){const found=M.propertyDefinition(D,fields,slot.property,slot.key),key=formulaKey(fields.LvlSetScript,slot.key,slot.property),draft=formulaDrafts.get(key);return {...found,script:found.script||(draft?{path:fields.LvlSetScript,evaluator:'floor-link'}:null),raw:draft?.after??found.definition?.raw,editKey:key,draft};}
 function level(){return Math.max(1,Math.min(1000,Number($('level').value)||1));}
 function evaluated(fields,slot){const def=definition(fields,slot);if(!def.raw)return {unknown:'Không resolve được bảng Lua',...def};if(def.script?.evaluator!=='floor-link')return {unknown:'Hàm GetSkillLevelData chưa hỗ trợ đánh giá',...def};return {...M.evaluate(def.raw,level()),...def};}
 function renderDamage(){
  const s=current();$('formula-script').replaceChildren(fieldControl('LvlSetScript',s.fields.LvlSetScript,v=>{editSkill('LvlSetScript',v);renderDamage();renderLayers();}));
  const fragment=document.createDocumentFragment(),visible=M.slots(s.fields).filter(slot=>$('all-slots').checked||slot.property||s.isNew);
  visible.forEach(slot=>{const box=node('section',undefined,'formula-card');box.append(node('strong','Ô '+slot.slot+' · '+(M.statLabels[slot.property]||slot.property||'Thêm thuộc tính')));
   const controls=node('div',undefined,'fieldgrid');controls.append(fieldControl('LvlSetting'+slot.slot,slot.property,v=>{editSkill('LvlSetting'+slot.slot,v);if(v&&!current().fields['LvlData'+slot.slot])editSkill('LvlData'+slot.slot,'skill_'+selected);renderDamage();renderLayers();}),fieldControl('LvlData'+slot.slot,slot.key,v=>{editSkill('LvlData'+slot.slot,v);renderDamage();renderLayers();}));box.append(controls);
   if(slot.property){const result=evaluated(s.fields,slot);box.append(node('p',result.values?'Cấp '+level()+' → P1: '+result.values[0]+' · P2: '+result.values[1]+' · P3: '+result.values[2]:'Chưa tính: '+result.unknown,result.values?'formula-result':'muted'));
    const area=document.createElement('textarea');area.rows=3;area.value=result.raw||'{{{1,0},{20,0}}}';area.setAttribute('aria-label','Bảng Lua '+slot.property+' ô '+slot.slot);
    const builder=node('details',undefined,'new-curve');builder.open=!result.raw;builder.append(node('summary','Nhập giá trị theo cấp cho P1 / P2 / P3'));const grid=node('div',undefined,'fieldgrid'),starts=[],ends=[];
    for(let p=0;p<3;p++){const col=node('div'),a=document.createElement('input'),b=document.createElement('input');a.type=b.type='number';a.value=b.value='0';a.step=b.step='any';a.setAttribute('aria-label','P'+(p+1)+' tại cấp 1');b.setAttribute('aria-label','P'+(p+1)+' tại cấp tối đa');starts.push(a);ends.push(b);const la=node('label','P'+(p+1)+' · cấp 1'),lb=node('label','P'+(p+1)+' · cấp '+Math.max(2,Number(s.fields.MaxLevel)||20));la.append(a);lb.append(b);col.append(la,lb);grid.append(col);}
    builder.append(grid,makeButton('Đưa các mốc vào bảng',()=>{const end=Math.max(2,Number(s.fields.MaxLevel)||20);area.value='{'+starts.map((a,i)=>'{{1,'+(Number(a.value)||0)+'},{'+end+','+(Number(ends[i].value)||0)+'}}').join(',')+'}';}));box.append(builder);
    if(result.definition)box.append(node('small',result.script.path+':'+result.definition.line+(result.definition.duplicates?' · định nghĩa cuối sau khóa trùng':''),'codepath'));
    const feedback=node('small');const save=makeButton(result.definition?'Lưu bảng số vào draft':'Tạo bảng số mới',()=>{try{
      if(!s.fields.LvlSetScript||!/^[_a-zA-Z][_a-zA-Z0-9]*$/.test(slot.key)||!/^[_a-zA-Z][_a-zA-Z0-9]*$/.test(slot.property))throw Error('Cần đường dẫn Lua và khóa/thuộc tính là định danh Lua hợp lệ.');
      const evaluated=M.evaluate(area.value,level());if(evaluated.unknown)throw Error(evaluated.unknown);
      const users=allSkills().filter(x=>x.fields.LvlSetScript===s.fields.LvlSetScript&&M.slots(x.fields).some(t=>t.key===slot.key&&t.property===slot.property)).map(x=>x.id);
      formulaDrafts.set(result.editKey,{isNew:!result.definition,source:result.script?.path||s.fields.LvlSetScript,script:s.fields.LvlSetScript,key:slot.key,property:slot.property,line:result.definition?.line??null,byteStart:result.definition?.byteStart??null,byteEnd:result.definition?.byteEnd??null,sourceHash:result.script?.sha256??null,before:result.definition?.raw??null,after:area.value,users});
      renderPreview();renderDiff();renderDamage();renderLayers();status('Đã lưu công thức '+slot.property+' · '+users.length+' skill tham chiếu');
     }catch(error){feedback.textContent=error.message;}});box.append(area,save,feedback,node('small','P1/P2/P3 có nghĩa riêng cho từng thuộc tính. Bảng số mới là khai báo draft; backend cần tạo Lua 4 hoàn chỉnh.','field-hint'));
   }fragment.append(box);
  });if(!visible.length)fragment.append(node('p','Bật “Hiện đủ 20 ô” để thêm thuộc tính.','empty'));$('damage-rows').replaceChildren(fragment);
 }
 function skillLinks(s){const list=M.links(s.fields);for(const slot of M.slots(s.fields).filter(x=>/skill_(start|fly|collide|vanished)event$/.test(x.property))){const result=evaluated(s.fields,slot);if(result.values&&result.values[2]>0)list.push({id:result.values[2],kind:'skill',field:slot.property,label:'Lua '+slot.property,enabled:result.values[0]!==0});}return list;}
 function renderLayers(){const fragment=document.createDocumentFragment();const walk=(id,depth,seen,label,enabled)=>{const s=skill(id),row=node('div',undefined,'layer-node');row.style.marginLeft=Math.min(depth,4)*12+'px';row.append(node('small','Tầng liên kết '+(depth+1)+' · '+label+(enabled===false?' · TẮT':'')));if(!s){row.append(node('strong','#'+id+' · thiếu ID'));fragment.append(row);return;}row.append(makeButton('#'+id+' · '+s.fields.SkillName,()=>choose(id),'link-button'));fragment.append(row);if(seen.has(id)){row.append(node('small','Vòng lặp · dừng'));return;}if(depth>=7){row.append(node('small','Giới hạn độ sâu 8'));return;}const next=new Set(seen);next.add(id);for(const link of skillLinks(s)){if(link.kind==='skill')walk(link.id,depth+1,next,link.label,link.enabled);else{const m=missileDrafts.get(link.id)||missiles.get(link.id);const leaf=node('div','↳ Missile #'+link.id+' · '+(m?.fields.MissleName||'không tìm thấy'),'missile-leaf');leaf.style.marginLeft=(Math.min(depth,4)+1)*12+'px';fragment.append(leaf);}}};walk(selected,0,new Set(),'skill đang chọn',true);$('layer-tree').replaceChildren(fragment);}
 function linkedMissiles(){const ids=new Set(),visited=new Set();function walk(id,depth){if(visited.has(id)||depth>7)return;visited.add(id);const s=skill(id);if(!s)return;for(const link of skillLinks(s)){if(link.kind==='missile')ids.add(link.id);else walk(link.id,depth+1);}}walk(selected,0);return [...ids];}
 function renderMissile(){const ids=linkedMissiles();if(!ids.includes(missileId))missileId=ids[0]??null;const select=$('missile-select');select.replaceChildren();if(!ids.length){select.append(node('option','Không tìm thấy mẫu đạn trong chuỗi đã resolve'));$('missile-info').textContent='Kiểm tra ChildSkillId, BaseSkill/ByMissle và các tầng sự kiện. Không tự gán một missile tùy ý.';$('missile-fields').replaceChildren();return;}for(const id of ids){const o=node('option','#'+id+' · '+((missileDrafts.get(id)||missiles.get(id))?.fields.MissleName||'thiếu đường đạn'));o.value=id;select.append(o);}select.value=missileId;renderMissileFields();}
 function renderMissileFields(){const m=missileDrafts.get(missileId)||missiles.get(missileId);if(!m){$('missile-fields').replaceChildren();$('missile-info').textContent='ID missile không có trong missles.txt';return;}const users=allSkills().filter(s=>M.childTarget(s.fields)?.kind==='missile'&&Number(s.fields.ChildSkillId)===missileId).map(s=>s.id);$('missile-info').textContent=(m.isNew?'Đường đạn mới':'missles.txt:'+m.line)+' · '+users.length+' skill tham chiếu trực tiếp. Sửa mẫu này tác động mọi skill dùng chung. Các giá trị Lua có thể ghi đè.';const fragment=document.createDocumentFragment();const used=new Set(['MissleId']);const groups=[...S.missileGroups,{title:'SPR / sound theo từng pha',fields:D.missileHeaders.filter(k=>/^(AnimFile|SndFile)/.test(k))}];for(const group of groups){fragment.append(node('h3',group.title,'subheading'));const grid=node('div',undefined,'fieldgrid');for(const key of group.fields){if(!D.missileHeaders.includes(key))continue;used.add(key);grid.append(fieldControl(key,m.fields[key],value=>{const draft=clone(missileDrafts.get(missileId)||missiles.get(missileId));draft.fields[key]=value;missileDrafts.set(missileId,draft);renderDiff();previewCast();status('Draft missile #'+missileId+' · '+key);}));}fragment.append(grid);}for(const key of D.missileHeaders.filter(k=>!used.has(k)))fragment.append(fieldControl(key,m.fields[key],value=>{const draft=clone(missileDrafts.get(missileId)||missiles.get(missileId));draft.fields[key]=value;missileDrafts.set(missileId,draft);renderDiff();}));$('missile-fields').replaceChildren(fragment);}
 function renderAssets(){const q=$('icon-search').value.toLowerCase();const list=D.skills.filter(s=>s.icon&&(!q||s.fields.SkillName.toLowerCase().includes(q)||String(s.id).includes(q)||s.fields.SkillIcon.toLowerCase().includes(q))).slice(0,36);const fragment=document.createDocumentFragment();for(const s of list){const b=makeButton('',()=>{assetDrafts.delete(selected);editSkill('SkillIcon',s.fields.SkillIcon);renderGroup(S.groups.find(g=>g.key==='assets'));renderAssets();},'icon-choice');const icon=node('span',undefined,'skill-icon');drawIcon(icon,s);b.append(icon,node('small','#'+s.id+' '+s.fields.SkillName));b.setAttribute('aria-label','Dùng icon '+s.fields.SkillName);fragment.append(b);}$('icon-library').replaceChildren(fragment);}
 function renderRaw(){const query=$('raw-filter').value.toLowerCase();$('raw-fields').replaceChildren(...D.headers.filter(k=>k.toLowerCase().includes(query)).map(k=>fieldControl(k,current().fields[k],v=>editSkill(k,v),{readonly:k==='SkillId'})));}
 function statRow(parent,label,value){const row=node('div',undefined,'tooltip-stat');row.append(node('span',label),node('strong',String(value)));parent.append(row);}
 function renderPreview(){const s=current(),f=s.fields;drawIcon($('tooltip-icon'),s);$('tooltip-name').textContent=f.SkillName;$('tooltip-system').textContent=s.factionName+'\n'+clean(D.settings.SkillAttrib[f.Attrib]||f.Property);$('tooltip-desc').textContent=clean(f.SkillDesc);$('tooltip-values').replaceChildren();const weaponKey=f.EqtLimit==='-1'?'F1':f.EqtLimit==='-2'?'F2':f.EqtLimit;statRow($('tooltip-values'),'Vũ khí',clean(D.settings.WeaponLimit[weaponKey]||f.EqtLimit));statRow($('tooltip-values'),'Cấp nhân vật',f.ReqLevel);statRow($('tooltip-values'),'Cấp xem / tối đa',level()+' / '+f.MaxLevel);statRow($('tooltip-values'),'Tầm đánh gốc',f.AttackRadius);statRow($('tooltip-values'),'Tiêu hao gốc',f.CostValue);
  $('tooltip-damage').replaceChildren();for(const slot of M.slots(f).filter(x=>x.property)){const result=evaluated(f,slot);if(result.values)statRow($('tooltip-damage'),M.statLabels[slot.property]||slot.property,result.values.join(' / '));else statRow($('tooltip-damage'),M.statLabels[slot.property]||slot.property,'Chưa tính');}
  $('provenance').replaceChildren(node('strong',s.isNew?'Workspace · skill mới từ đầu':D.source+':'+s.line),node('span',s.isNew?'Tên / nội dung do người tạo nhập':'SkillName · TCVN3 / bytes gốc'),node('span',s.factionEvidence),node('span',s.learn?s.learn.source+':'+s.learn.line:f.LvlSetScript),node('span',s.icon?.match||'Chưa resolve icon'),node('span','Không chứng minh nhân vật live đã học skill.'));
 }
 function changedSkills(){return [...drafts.values()].filter(s=>s.isNew||M.diff(baseline(s),s.fields).length);}
 function changedMissiles(){return [...missileDrafts.values()].filter(m=>m.isNew||M.diff(missileBaseline(m),m.fields).length);}
 function changedFormulas(){return [...formulaDrafts.values()].filter(f=>f.before!==f.after);}
 function renderDiff(){const s=current(),rows=M.diff(baseline(s),s.fields);$('diff-count').textContent=rows.length+(s.isNew?1:0);const fragment=document.createDocumentFragment();if(s.isNew)fragment.append(node('p','Skill mới #'+selected+' · khai báo từ đầu, tài nguyên do người tạo chọn'));for(const r of rows){const row=node('div',undefined,'diffrow');row.append(node('strong',r.field),node('div',r.before||'(rỗng)','before'),node('div','→ '+r.after,'after'));fragment.append(row);}if(!rows.length&&!s.isNew)fragment.append(node('p','Chưa đổi cột của skill này. Công thức, missile và ảnh được liệt kê ở Thay đổi & xuất.','empty'));$('diff-body').replaceChildren(fragment);renderRelease();}
 function renderRelease(){const skills=changedSkills(),ms=changedMissiles(),formulas=changedFormulas();$('release-summary').textContent=skills.length+' skill · '+ms.length+' missile · '+formulas.length+' bảng Lua · '+assetDrafts.size+' ảnh thử';const fragment=document.createDocumentFragment();for(const s of skills)fragment.append(node('div','#'+s.id+' '+s.fields.SkillName+' · '+(s.isNew?'Tạo mới':M.diff(baseline(s),s.fields).length+' cột'),'detailrow'));for(const m of ms)fragment.append(node('div','Missile #'+m.id+' · '+M.diff(missileBaseline(m),m.fields).length+' cột','detailrow'));for(const f of formulas)fragment.append(node('div',f.property+' / '+f.key+' · tham chiếu bởi '+f.users.join(', '),'detailrow'));for(const [id,a]of assetDrafts)fragment.append(node('div','Ảnh thử #'+id+' · '+a.name+' · cần chuyển SPR','detailrow'));$('release-list').replaceChildren(fragment);scheduleWorkspace();}
 async function exportAll(){try{commitInput();const report=runValidation(),payload={format:'jx-skill-studio-draft/v0.4',deployable:false,snapshotId:D.snapshotId,source:D.source,exportedAt:new Date().toISOString(),skills:changedSkills().map(s=>({id:s.id,isNew:!!s.isNew,creation:s.isNew?'blank':undefined,faction:s.faction,sourceLine:s.line,fields:M.diff(baseline(s),s.fields),draft:s.fields})),missiles:changedMissiles().map(m=>({id:m.id,isNew:!!m.isNew,source:D.missileSource,line:m.line,fields:M.diff(missileBaseline(m),m.fields),draft:m.fields})),formulas:workspaceState().formulas,assets:[...assetDrafts].map(([skillId,a])=>({skillId,...a,requiresSprConversion:true})),validation:report,warnings:['Snapshot loose files; chưa xác minh PAK precedence/live','Skill mới cần cấu hình học và xác minh giới hạn ID','Không tự áp dụng gói này lên game'],workspace:captureWorkspace()};const result=await P.exportDraft(payload);status(result.canceled?'Đã hủy xuất.':'Đã xuất changeset · '+report.errors+' lỗi / '+report.warnings+' lưu ý · deployable=false');}catch(e){workspaceError(e);}}
 function openCreate(kind){createKind=kind;creationParent=selected;const isMissile=kind==='missile';const used=isMissile?[...missiles.keys(),...missileDrafts.keys()]:[...originals.keys(),...drafts.keys()];const floor=Math.max(0,...used)+1;$('create-id').value=M.nextDraftId(used,floor);$('create-name').value='';$('create-title').textContent=isMissile?'Tạo đường đạn mới':kind==='layer'?'Tạo tầng skill mới':'Tạo skill mới';$('create-description').textContent=(isMissile?'Đường đạn bắt đầu trống và được gắn vào ChildSkillId của skill #'+selected+'. Liên kết ChildSkillId hiện tại sẽ được thay thế.':kind==='layer'?'Tạo một SkillId trống rồi gắn vào sự kiện bạn chọn của #'+selected+'. Liên kết tại vị trí đó sẽ được thay thế.':'Nhập ID, tên và môn phái. Bạn sẽ tự chọn loại skill, action, sát thương, các tầng, icon và hiệu ứng.')+' ID đề xuất dựa trên catalog + draft hiện tại; giới hạn engine vẫn cần kiểm tra.';$('create-faction-label').hidden=isMissile;$('create-link-label').hidden=kind!=='layer';$('create-faction').value='';$('create-link').value='ChildSkillId';$('create-error').textContent='';$('create-dialog').showModal();}
 $('new-skill').onclick=()=>openCreate('skill');$('new-layer').onclick=()=>openCreate('layer');$('new-missile').onclick=()=>openCreate('missile');
 $('create-cancel').onclick=()=>$('create-dialog').close();
 $('create-form').onsubmit=e=>{e.preventDefault();const id=Number($('create-id').value),name=$('create-name').value.trim(),isMissile=createKind==='missile';if(!Number.isSafeInteger(id)||id<=0||(isMissile?(missiles.has(id)||missileDrafts.has(id)):originals.has(id))||!name){$('create-error').textContent='ID phải là số nguyên dương chưa có; tên không được rỗng.';return;}
  if(isMissile){const m=M.newMissile(D,id,name);missileDrafts.set(id,m);const parent=clone(skill(creationParent));Object.assign(parent.fields,{BaseSkill:'1',ByMissle:'1',ChildSkillId:String(id),ChildSkillNum:'1'});drafts.set(parent.id,parent);selected=parent.id;missileId=id;}
  else{const created=M.newSkill(D,{id,name,faction:$('create-faction').value});originals.set(id,clone(created));drafts.set(id,created);if(createKind==='layer'){const parent=clone(skill(creationParent)),field=$('create-link').value,flag={StartSkillId:'StartEvent',FlySkillId:'FlyEvent',CollidSkillId:'CollideEvent',VanishedSkillId:'VanishedEvent'}[field];parent.fields[field]=String(id);if(flag)parent.fields[flag]='1';else Object.assign(parent.fields,{BaseSkill:'0',ByMissle:'0',ChildSkillNum:'1',ChildSkillLevel:'1'});drafts.set(parent.id,parent);}selected=id;$('scope').value='';$('faction').value='';$('search').value=String(id);}
  $('create-dialog').close();renderList();renderEditor();if(isMissile)selectTab('missile');status('Đã tạo '+(isMissile?'đường đạn':'skill')+' mới #'+id);
 };
 function showResources(preferred){const q=$('resource-search').value.toLowerCase(),list=resourceOptions().filter(r=>!q||(r.label+' '+r.value).toLowerCase().includes(q)),select=$('resource-select'),value=typeof preferred==='string'?preferred:select.value;select.replaceChildren();for(const r of list){const o=node('option',r.label);o.value=r.value;select.append(o);}select.value=list.some(r=>r.value===value)?value:list[0]?.value||'';$('resource-count').textContent=list.length+' kết quả · '+C.resources.filter(r=>r.status==='ready').length+' SPR đã giải mã / '+C.resources.length+' tham chiếu';$('resource-apply').disabled=!select.value;showResourcePreview();}
 function showResourcePreview(){const raw=$('resource-select').value;raw?resourceAnimation.show(raw,'SPR đang chọn'):resourceAnimation.explain('Không có tài nguyên khớp.');}
 function openResource(value,save){resourceSave=save;$('resource-search').value='';showResources(value);$('resource-dialog').showModal();}
 $('resource-search').oninput=showResources;$('resource-select').onchange=showResourcePreview;
 $('resource-cancel').onclick=()=>{$('resource-dialog').close();resourceAnimation.stop();};$('resource-dialog').onclose=()=>resourceAnimation.stop();
 $('resource-apply').onclick=()=>{const value=$('resource-select').value;if(value&&resourceSave)resourceSave(value);$('resource-dialog').close();resourceAnimation.stop();};
 function renderPoses(){const p=C.profiles.find(p=>p.key===$('preview-character').value)||C.profiles[0];$('preview-pose').replaceChildren();for(const pose of p.poses){const o=node('option',pose.label);o.value=pose.value;$('preview-pose').append(o);}$('preview-pose').value='0';}
 for(const p of C.profiles){const o=node('option',p.label);o.value=p.key;$('preview-character').append(o);}$('preview-character').value=C.profiles[0].key;renderPoses();
 $('preview-character').onchange=()=>{renderPoses();previewAction();};$('preview-pose').onchange=()=>previewAction();$('action-cast-overlay').onchange=()=>previewAction();$('action-interval').oninput=()=>previewAction();$('cast-stage').onchange=()=>showCastStage();$('cast-interval').oninput=()=>{showCastStage();};
 $('undo').onclick=()=>{const s=current();assetDrafts.delete(selected);drafts.delete(selected);if(s.isNew){originals.delete(selected);for(const [id,other]of drafts){for(const link of M.links(other.fields).filter(x=>x.kind==='skill'&&x.id===selected)){other.fields[link.field]=originals.get(id)?.isNew?'0':originals.get(id)?.fields[link.field]||'0';const flag={StartSkillId:'StartEvent',FlySkillId:'FlyEvent',CollidSkillId:'CollideEvent',VanishedSkillId:'VanishedEvent'}[link.field];if(flag)other.fields[flag]=originals.get(id)?.isNew?'0':originals.get(id)?.fields[flag]||'0';}}for(const [key,f]of formulaDrafts)if(f.isNew&&!allSkills().some(x=>x.fields.LvlSetScript===f.script&&M.slots(x.fields).some(slot=>slot.property===f.property&&slot.key===f.key)))formulaDrafts.delete(key);selected=4;}renderList();renderEditor();status('Đã hoàn tác skill. Lua/missile dùng chung giữ ở changeset riêng.');};
 $('undo-all').onclick=()=>{for(const [id,s]of originals)if(s.isNew)originals.delete(id);drafts.clear();missileDrafts.clear();formulaDrafts.clear();assetDrafts.clear();if(!originals.has(selected))selected=4;renderList();renderEditor();status('Đã hoàn tác toàn bộ draft trong phiên');};
 $('export').onclick=exportAll;$('export-all').onclick=exportAll;
 $('level').onchange=()=>{$('level').value=level();renderDamage();renderLayers();renderMissile();renderPreview();};$('all-slots').onchange=renderDamage;
 $('search').oninput=()=>{limit=80;renderList();};$('faction').onchange=()=>{limit=80;renderList();};$('scope').onchange=()=>{limit=80;renderList();};$('raw-filter').oninput=renderRaw;$('icon-search').oninput=renderAssets;
 $('missile-select').onchange=()=>{missileId=Number($('missile-select').value);renderMissileFields();};
 $('icon-file').onchange=async()=>{const file=$('icon-file').files[0];if(!file)return;if(file.size>2*1024*1024||!['image/png','image/jpeg'].includes(file.type)){status('Chỉ nhận PNG/JPEG tối đa 2 MB');return;}const target=selected,reader=new FileReader();reader.onload=()=>{assetDrafts.set(target,{name:file.name,mime:file.type,preview:reader.result});if(selected===target){renderHeader();renderPreview();}renderList();renderRelease();status('Ảnh thử đã đổi · chưa chuyển SPR');};reader.readAsDataURL(file);};
 $('theme').onchange=()=>$('studio').classList.toggle('bronze',$('theme').value==='bronze');
 $('update-check').onclick=async()=>{const b=$('update-check');b.disabled=true;updateState('Đang kiểm tra cập nhật…');try{const result=await P.checkForUpdates();if(result?.status==='browser-demo')updateState('Bản demo trình duyệt · dùng EXE để cập nhật');else if(result?.status==='up-to-date')updateState('Đã kiểm tra · bản '+(result.version||'hiện tại'));}catch(e){updateState('Cập nhật lỗi · '+e.message);status(e.message);}finally{b.disabled=false;}};
 $('ssh-check').onclick=()=>{const host=$('ssh-host').value.trim(),user=$('ssh-user').value.trim(),port=Number($('ssh-port').value);$('ssh-result').textContent=host&&user&&Number.isInteger(port)&&port>0&&port<=65535?'Form hợp lệ · chưa kết nối SSH hoặc xác minh fingerprint.':'Điền host, tài khoản và port 1–65535.';};
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!=='page-'+b.dataset.page);document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('selected',x===b));renderRelease();});
 function selectTab(tab){activeTab=tab;document.querySelectorAll('.tabpanel').forEach(p=>p.hidden=p.id!=='tab-'+activeTab);document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x.dataset.tab===tab);x.setAttribute('aria-selected',String(x.dataset.tab===tab));});}
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{selectTab(b.dataset.tab);renderEditor();});
 function workspaceState(){const all=allSkills();return {skills:changedSkills(),missiles:changedMissiles(),formulas:changedFormulas().map(f=>({...f,users:all.filter(s=>s.fields.LvlSetScript===f.script&&M.slots(s.fields).some(t=>t.key===f.key&&t.property===f.property)).map(s=>s.id)})),assets:[...assetDrafts].map(([skillId,a])=>({skillId,...a})),selection:selected,settings:{theme:$('theme').value,level:level(),query:$('search').value,faction:$('faction').value,scope:$('scope').value,tab:activeTab}};}
 function captureWorkspace(){return W.pack(D,workspaceState());}
 function contentKey(){const value=captureWorkspace();delete value.savedAt;return JSON.stringify(value);}
 function workspaceError(e){$('workspace-error').textContent=e.message;$('save-state').textContent='Chưa lưu · xem Thay đổi & xuất';status(e.message);}
 const autosave=W.autosaver(payload=>{W.unpack(payload,D);return P.writeAutosave(payload);},captureWorkspace,(phase,error)=>{
  $('save-state').textContent={dirty:'Có thay đổi · chờ tự lưu',saving:'Đang tự lưu…',saved:'Đã tự lưu',error:'Tự lưu thất bại'}[phase];
  if(error)workspaceError(error);
 });
 function scheduleWorkspace(){if(!workspaceLoaded)return;const key=contentKey();if(key===lastContent)return;lastContent=key;validation=null;$('validation-summary').textContent='Dữ liệu đã đổi · cần kiểm tra lại.';$('validation-list').replaceChildren();if(autosave.ready)autosave.changed();else $('save-state').textContent='Bản nháp chưa lưu · Lưu workspace';}
 function commitInput(){document.activeElement?.blur?.();scheduleWorkspace();}
 function applyWorkspace(state){
  workspaceLoaded=false;for(const [id,s]of originals)if(s.isNew)originals.delete(id);drafts.clear();missileDrafts.clear();formulaDrafts.clear();assetDrafts.clear();
  for(const s of state.skills){if(s.isNew)originals.set(s.id,clone(s));drafts.set(s.id,s);}for(const m of state.missiles)missileDrafts.set(m.id,m);for(const f of state.formulas)formulaDrafts.set(W.formulaKey(f),f);for(const a of state.assets){const {skillId,...asset}=a;assetDrafts.set(skillId,asset);}
  selected=state.selection;missileId=null;limit=80;const v=state.settings;
  for(const [id,key]of [['theme','theme'],['level','level'],['search','query'],['faction','faction'],['scope','scope']])$(id).value=v[key];
  $('studio').classList.toggle('bronze',v.theme==='bronze');selectTab(v.tab);renderList();renderEditor();validation=null;$('validation-list').replaceChildren();$('validation-summary').textContent='Workspace vừa mở · bấm Kiểm tra dữ liệu.';
  workspaceLoaded=true;lastContent=contentKey();
 }
 function showPage(page){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!=='page-'+page);document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('selected',b.dataset.page===page));}
 function showIssue(issue){
  showPage('library');if(issue.kind==='skill'&&originals.has(issue.id)){choose(issue.id);const group=S.groups.find(g=>g.fields.includes(issue.field));selectTab(/^Lvl/.test(issue.field)?'damage':group?.key||'raw');}
  else if(issue.kind==='missile'){missileId=issue.id;selectTab('missile');renderMissileFields();}else selectTab('damage');
  status((issue.id?'#'+issue.id+' · ':'')+issue.field+': '+issue.message);
 }
 function runValidation(){validation=V.validate(D,C,workspaceState());$('validation-summary').textContent=validation.errors+' lỗi · '+validation.warnings+' lưu ý · '+validation.checkedSkills+' skill / '+validation.checkedMissiles+' missile đã kiểm tra. '+(validation.truncated?'Danh sách đã giới hạn 1.500 mục. ':'')+'Kết quả chưa xác nhận chạy đúng trên engine.';const fragment=document.createDocumentFragment();for(const issue of validation.issues){const row=node('div',undefined,'validation-issue '+issue.severity);row.append(node('strong',issue.severity==='error'?'LỖI':'LƯU Ý'),makeButton((issue.id?'#'+issue.id+' · ':'')+issue.field,()=>showIssue(issue),'link-button'),node('p',issue.message));fragment.append(row);}$('validation-list').replaceChildren(fragment);return validation;}
 $('validate').onclick=()=>{commitInput();runValidation();};
 $('workspace-save').onclick=async()=>{try{commitInput();const payload=captureWorkspace(),key=contentKey();W.unpack(payload,D);const result=await P.saveAs(payload);if(result.canceled){status('Đã hủy lưu workspace.');return;}manualSavedContent=key;if(autosave.ready)await autosave.flush();$('workspace-error').textContent='';$('save-state').textContent=result.downloaded?'Đã yêu cầu tải workspace':'Đã lưu workspace';status(result.path?'Đã lưu '+result.path:'Đã tải workspace; giữ tệp .jxworkspace để mở lại.');}catch(e){workspaceError(e);}};
 $('workspace-open').onclick=async()=>{try{const result=await P.openFile();if(result.canceled)return;const state=W.unpack(result.workspace,D);pendingWorkspace=state;$('workspace-preview').textContent=(result.path||'Workspace')+' · '+state.skills.length+' skill / '+state.missiles.length+' missile / '+state.formulas.length+' bảng Lua / '+state.assets.length+' ảnh.'+(state.legacy?' Changeset v0.3: đã đối chiếu before với snapshot.':' Snapshot khớp.');$('workspace-dialog-error').textContent='';$('workspace-dialog').showModal();}catch(e){workspaceError(e);}};
 $('workspace-cancel').onclick=()=>{pendingWorkspace=null;$('workspace-dialog').close();};
 $('workspace-apply').onclick=async()=>{if(!pendingWorkspace)return;$('workspace-apply').disabled=true;try{
  commitInput();if(autosave.ready){autosave.changed();await autosave.flush();}else if(manualSavedContent!==contentKey())throw Error('Tự lưu chưa khả dụng. Hủy hộp này và Lưu workspace đang mở trước khi thay thế.');
  applyWorkspace(pendingWorkspace);pendingWorkspace=null;$('workspace-dialog').close();if(autosave.ready){autosave.changed();await autosave.flush();}else $('save-state').textContent='Workspace đã mở · chưa tự lưu';status('Đã mở workspace để tiếp tục chỉnh sửa.');
 }catch(e){$('workspace-dialog-error').textContent=e.message;workspaceError(e);}finally{$('workspace-apply').disabled=false;}};
 $('scan-local').onclick=async()=>{$('scan-local').disabled=true;$('scan-state').textContent='Đang quét…';try{const r=await P.scan();$('scan-state').textContent='Quét lúc '+new Date(r.observedAt).toLocaleString('vi-VN')+' · '+r.clients.length+' tiến trình phù hợp';const fragment=document.createDocumentFragment();for(const c of r.clients)fragment.append(node('p',(c.name||'Client')+' · PID '+(c.Id??c.id)+' · '+(c.executable||c.error)+' · '+(c.schemaMatched?'Có schema SkillId':'Chưa xác nhận schema'),'scan-client'));fragment.append(node('h3','WSL'),node('pre',r.wsl.text,'scan-wsl'),node('p',r.note,'muted'));$('scan-result').replaceChildren(fragment);}catch(e){$('scan-state').textContent=e.message;}finally{$('scan-local').disabled=false;}};
 async function initializeWorkspace(){
  $('studio').inert=true;try{const info=await P.info();$('workspace-info').textContent=info.mode+' · '+(info.dataRoot||'Kho trình duyệt')+' · Snapshot '+D.snapshotId.slice(0,12);const saved=await P.readAutosave();if(saved.workspace)applyWorkspace(W.unpack(saved.workspace,D));autosave.enable();$('save-state').textContent=saved.workspace?'Đã khôi phục workspace':'Workspace mới · tự lưu sẵn sàng';if(saved.warning)$('workspace-error').textContent=saved.warning;
  }catch(e){autosave.disable();workspaceError(e);}finally{workspaceLoaded=true;lastContent=contentKey();$('studio').inert=false;}
 }
 document.addEventListener?.('change',scheduleWorkspace);
 P.onClosing(async()=>{try{await window.JXReady;commitInput();if(autosave.ready)await autosave.flush();else if(manualSavedContent!==contentKey()&&(changedSkills().length||changedMissiles().length||changedFormulas().length||assetDrafts.size))throw Error('Bản nháp chưa lưu.');await P.closeReady();}catch(e){workspaceError(e);await P.closeFailed();}});
 window.addEventListener?.('beforeunload',e=>{commitInput();if(autosave.dirty||(!autosave.ready&&manualSavedContent!==contentKey()&&(changedSkills().length||changedMissiles().length||changedFormulas().length||assetDrafts.size))){autosave.flush().catch(()=>{});e.preventDefault();e.returnValue='';}});
 for(const f of D.factions){const count=D.skills.filter(s=>s.faction===f.key).length;const option=node('option',f.name+' · '+count);option.value=f.key;$('faction').append(option);const createOption=node('option',f.name);createOption.value=f.key;$('create-faction').append(createOption);}
 $('coverage').textContent=D.coverage.rows+' ID client · '+D.coverage.learned+' có lệnh học · '+D.coverage.missiles+' mẫu đường đạn';
 $('audit-summary').append(node('p',D.coverage.rawRows+' dòng skill / '+D.coverage.rows+' ID duy nhất. '+D.duplicates.map(x=>'ID '+x.id+' trùng tại dòng '+x.lines.join(', ')).join('; ')+'; bản xem chọn dòng cuối, chưa xác minh cách engine xử lý. Không triển khai trực tiếp.'),node('p',D.coverage.factions+' tên phái trong faction INI; không khẳng định tất cả được bật trong game. '+D.coverage.scripts+' script tham chiếu tìm được. Tên gốc có dấu (##), dữ liệu kỹ thuật hoặc chưa phân loại vẫn được giữ trong phạm vi riêng.'));
 document.querySelectorAll('.tabpanel').forEach(p=>p.hidden=p.id!=='tab-general');renderList();renderEditor();window.JXReady=initializeWorkspace();
})();
