window.JX_SCHEMA={
 groups:[
  {key:'general',title:'Định danh & hiển thị',fields:['SkillName','Property','Attrib','SkillDesc','ReqLevel','MaxLevel','Series','EqtLimit','HorseLimit','SkillStyle','IsExpSkill','ShowAddition','ShowEvent','LevelUpScript']},
  {key:'combat',title:'Tầm đánh, mục tiêu & cast',fields:['AttackRadius','SkillCostType','CostValue','TimePerCast','TimePerCastOnHorse','WaitTime','CharAnimId','IsMelee','IsPhysical','IsUseAR','DoHurt','LRSkill','TargetOnly','TargetEnemy','TargetAlly','TargetSelf','TargetOther','TargetObj','TargetNoNpc','PeaceCanUse','ClientSend','WeaponSkill','CharClass']},
  {key:'layers',title:'Tầng, chiêu con & sự kiện',fields:['BaseSkill','ByMissle','ChildSkillId','ChildSkillLevel','ChildSkillNum','MslsGenerate','MslsGenerateData','MisslesForm','Param1','Param1Memo','Param2','Param2Memo','EventSkillLevel','StartEvent','StartSkillId','FlyEvent','FlySkillId','FlyEventTime','CollideEvent','CollidSkillId','VanishedEvent','VanishedSkillId','StopWhenMove','HeelAtParent','RelativePosType']},
  {key:'assets',title:'Icon, hiệu ứng & âm thanh',fields:['SkillIcon','PreCastSpr','ManCastSnd','FMCastSnd','StateSpecialId','StatePriority','IsAura','NeedShadow','MaxShadowNum']}
 ],
 missileGroups:[
  {title:'Đường bay & thời gian',fields:['MissleName','MoveKind','FollowKind','ColFollowTarget','MissleHeight','Speed','Zspeed','Zacc','LifeTime','Param1','Param2','Param3']},
  {title:'Va chạm & vùng sát thương',fields:['CollidRange','IsRangeDmg','DmgRange','DmgInterval','ResponseSkill','CanDestroy','ColVanish','CanSlow','CanColFriend','AutoExplode','MissRate','MultiShow']},
  {title:'Animation & ánh sáng',fields:['LoopPlay','SubLoop','SubStart','SubStop','RedLum','GreenLum','BlueLum','LightRadius']}
 ],
 labels:{SkillName:'Tên hiển thị',Property:'Tính chất skill',Attrib:'Nhánh võ công (client)',SkillDesc:'Mô tả / markup tooltip',ReqLevel:'Cấp nhân vật yêu cầu',MaxLevel:'Cấp skill tối đa',Series:'Ngũ hành',EqtLimit:'Vũ khí',HorseLimit:'Giới hạn cưỡi ngựa',SkillStyle:'Loại skill',IsExpSkill:'Skill luyện kinh nghiệm',ShowAddition:'Hiển thị hỗ trợ',ShowEvent:'Hiển thị sự kiện',LevelUpScript:'Script tăng cấp',AttackRadius:'Tầm đánh gốc',SkillCostType:'Loại tiêu hao',CostValue:'Tiêu hao gốc',TimePerCast:'Khoảng cách mỗi lần cast',TimePerCastOnHorse:'Khoảng cast trên ngựa',WaitTime:'Độ chờ xuất chiêu',CharAnimId:'Action nhân vật',IsMelee:'Cận chiến',IsPhysical:'Vật lý',IsUseAR:'Dùng độ chính xác',DoHurt:'Tham số gây khựng',LRSkill:'Ô sử dụng skill',TargetOnly:'Một mục tiêu',TargetEnemy:'Đối địch',TargetAlly:'Đồng minh',TargetSelf:'Bản thân',TargetOther:'Đối tượng khác',TargetObj:'Vật thể',TargetNoNpc:'Không chọn NPC',PeaceCanUse:'Dùng ở hòa bình',ClientSend:'Client gửi lệnh',WeaponSkill:'Skill vũ khí',CharClass:'Hệ nhân vật (CharClass)',BaseSkill:'ChildSkillId trỏ tới missile',ByMissle:'Hiệu lực theo missile',ChildSkillId:'Đường đạn / chiêu con',ChildSkillLevel:'Cấp chiêu con',ChildSkillNum:'Số lượng chiêu con / đạn',MslsGenerate:'Cách sinh đạn',MslsGenerateData:'Khoảng sinh đạn',MisslesForm:'Dạng phân bố đạn',Param1:'Tham số góc / bố trí 1',Param2:'Tham số khoảng cách / bố trí 2',EventSkillLevel:'Cấp skill sự kiện',StartEvent:'Bật sự kiện xuất chiêu',StartSkillId:'Skill khi xuất chiêu',FlyEvent:'Bật sự kiện đạn bay',FlySkillId:'Skill khi đang bay',FlyEventTime:'Nhịp sự kiện bay',CollideEvent:'Bật sự kiện va chạm',CollidSkillId:'Skill khi va chạm',VanishedEvent:'Bật sự kiện tan biến',VanishedSkillId:'Skill khi tan biến',SkillIcon:'Đường dẫn icon SPR',PreCastSpr:'SPR trước cast',ManCastSnd:'Âm thanh nhân vật nam',FMCastSnd:'Âm thanh nhân vật nữ',StateSpecialId:'Hiệu ứng trạng thái',StatePriority:'Ưu tiên trạng thái',IsAura:'Aura',NeedShadow:'Dùng ảnh bóng',MaxShadowNum:'Số bóng tối đa',LvlSetScript:'Script công thức theo cấp',MissleName:'Tên mẫu đường đạn',MoveKind:'Kiểu chuyển động',FollowKind:'Kiểu bám mục tiêu',ColFollowTarget:'Va chạm theo mục tiêu',MissleHeight:'Độ cao đạn',Speed:'Tốc độ đạn gốc',Zspeed:'Vận tốc trục Z',Zacc:'Gia tốc trục Z',LifeTime:'Thời gian tồn tại',CollidRange:'Bán kính va chạm',IsRangeDmg:'Gây sát thương vùng',DmgRange:'Phạm vi sát thương',DmgInterval:'Nhịp gây sát thương',ResponseSkill:'Skill phản ứng',CanDestroy:'Có thể phá hủy',ColVanish:'Tan biến khi chạm',CanSlow:'Có thể làm chậm',CanColFriend:'Va chạm đồng minh',AutoExplode:'Tự nổ',MissRate:'Tỷ lệ hụt',MultiShow:'Hiển thị nhiều lớp',LoopPlay:'Lặp animation',SubLoop:'Lặp đoạn',SubStart:'Frame bắt đầu',SubStop:'Frame kết thúc',RedLum:'Ánh đỏ',GreenLum:'Ánh xanh lá',BlueLum:'Ánh xanh lam',LightRadius:'Bán kính sáng'},
 hints:{AttackRadius:'Lua skill_attackradius có thể ghi đè. Giữ đơn vị raw.',CostValue:'Lua skill_cost_v có thể ghi đè.',ChildSkillId:'Profile tham khảo: BaseSkill=1 hoặc ByMissle=1 → missles.txt; còn lại → skill. Cần đối chiếu engine cho trường hợp khác.',ChildSkillNum:'Lua missle_num có thể ghi đè.',DoHurt:'Không phải sát thương. Giữ raw; ý nghĩa timing phụ thuộc engine.',EventSkillLevel:'Giữ raw; xem thêm skill_eventskilllevel trong Lua.',HorseLimit:'Giữ giá trị nguồn; chưa gán nhãn Có/Không khi chưa xác minh enum.',Param1:'Ý nghĩa phụ thuộc MslsGenerate/MisslesForm; không có một đơn vị chung.',Param2:'Ý nghĩa phụ thuộc kiểu sinh và quỹ đạo.',SkillIcon:'Giữ đường dẫn byte GBK/Mojibake; không đổi tên thành Unicode tự động.',LifeTime:'Bảng gốc; Lua missle_lifetime_v có thể ghi đè.',Speed:'Bảng gốc; Lua missle_speed_v có thể ghi đè.',Attrib:'Nhãn lấy từ gamesetting.ini [SkillAttrib]. Không dùng để tự đoán môn phái.'}
};
